INSERT INTO Submitter(submitter_id, submitter_name, submitter_type) VALUES
(0, 'Admin', 'User');

INSERT INTO _User(submitter_id, email, session_secret) VALUES
(0, 'admin@gmail.com', '123456789');

INSERT INTO API(submitter_id, api_token) VALUES
(0, '123');

INSERT INTO Restaurant(restaurant_id, restaurant_name, latitude, longitude) VALUES
(0, 'restaurant_test', 0, 0);

INSERT INTO Cuisine(cuisine_name) VALUES
('African'),
('Alentejana'),
('American'),
('Angolan'),
('Arabian'),
('Argentine'),
('Asian'),
('Austrian'),
('Author'),
('BBQ'),
('Bakery'),
('Bangladeshi'),
('Bar Food'),
('Belgian'),
('Beverages'),
('Brazilian'),
('British'),
('Burger'),
('Cafe'),
('Cafe Food'),
('Canadian'),
('Cape Verdean'),
('Caribbean'),
('Chinese'),
('Coffee'),
('Coffee and Tea'),
('Contemporary'),
('Crepes'),
('Cuban'),
('Desserts'),
('Eastern European'),
('Filipino'),
('Finger Food'),
('French'),
('Fresh Fish'),
('Fusion'),
('Goan'),
('Gourmet Fast Food'),
('Greek'),
('Grill'),
('Healthy Food'),
('Ice Cream'),
('International'),
('Iranian'),
('Irish'),
('Israeli'),
('Italian'),
('Japanese'),
('Juices'),
('Kebab'),
('Korean'),
('Latin American'),
('Lebanese'),
('Madeiran'),
('Malaysian'),
('Mediterranean'),
('Mexican'),
('Middle Eastern'),
('Mineira'),
('Minhota'),
('Moroccan'),
('Mozambican'),
('Nepalese'),
('Oriental'),
('Pakistani'),
('Patisserie'),
('Peruvian'),
('Petiscos'),
('Pizza'),
('Portuguese'),
('Ramen'),
('Russian'),
('Salad'),
('Sandwich'),
('Santomean'),
('Seafood'),
('Snack Bar'),
('Snacks'),
('Spanish'),
('Steak'),
('Street Food'),
('Sushi'),
('Swedish'),
('Swiss'),
('Tapas'),
('Tea'),
('Thai'),
('Tibetan'),
('Transmontana'),
('Turkish'),
('Vegan'),
('Vegetarian'),
('Vietnamese');

INSERT INTO Meal(meal_id, meal_name, cuisine_name) VALUES
(0, 'mealExample', 'African');

INSERT INTO Ingredient(ingredient_id, ingredient_name) VALUES
(0, 'ingredientExample');